### PR TITLE
Fix astra ops

### PR DESCRIPTION
**Pull request by epapoutsellis**

### CODE REVIEW

**Comment by jakobsj** [comment]
Please could you add some information on what this PR fixes and how/why, such background would make it easier to review.

**Comment by epapoutsellis** [comment]
Main changes
1) Add multichannel operator for the 3D case
Basically, it creates the 3D AStraprojectorSimple operator
https://github.com/vais-ral/CCPi-astra/pull/33/files#diff-52d28e17339931564441f63664ab6541R43

and then uses direct/adjoint of the 3D operator and copies the output for each channel:

https://github.com/vais-ral/CCPi-astra/pull/33/files#diff-52d28e17339931564441f63664ab6541R55

https://github.com/vais-ral/CCPi-astra/pull/33/files#diff-52d28e17339931564441f63664ab6541R78

2) Fix the calculation of the AstraProjectorMC
https://github.com/vais-ral/CCPi-astra/pull/33/files#diff-e1c46a71dc079b201b1e863141dd7d49R71

I do not like the solution that I found, need a more flexible clone method, but atm it works

**Comment by jakobsj** [comment]
This PR seems related to #25 and #32. Please check for conflicts and make sure everything you wanted is included.  When merged, close all the PRs.

**Comment by paskino** [comment]
I haven't tested it but it seems ok.
What it missing are unit tests. Can I suppose the lines below `if __name__ == '__main__':` provide a minimal test?

**Comment by paskino** [comment]
closed by #36

**Pull request closed without merging**
